<div id="wrapfooter">
    <footer id="footer" role="contentinfo">
        <nav class=" ">

            © 2012 SNB, Inc.
        </nav>
        <section class="right">
            <div class="float_right">
                <small class="logo">
                    <a href="#" title=" ">
                        &nbsp;
                    </a>
                </small>
                <nav class="social">
                    <ul>
                        <li class="facebook"><a href="#" target="_blank" title="Facebook">Facebook</a></li>
                        <li class="twitter"><a href="#" target="_blank" title="LinkedIn">LinkedIn</a></li>
                        <li class="linkedin"><a href="#" target="_blank" title="Twitter">Twitter</a></li>
                    </ul>
                </nav>
            </div>
            <a class="verisign_verify" href="#"   target="_blank" title="Verisign Secure Verification">
                <img alt="Verisign Secure" src="<?=$this->baseUrl().'/images/verisign_verify.png'?>" />
            </a>
        </section>



    </footer>
</div>