

<div id="sidebar">
    <div class="sidebar_user">
        <div class="fields">
            <div class="input_set">
                <div class="input_set">
                    <p>
                    <div id="self_card">
                        <a href="#" ><img alt="Default_thumb" class="avatar_thumb" src="<?=
$this->baseUrl() . '/images/Profil/' . $this->escape($GLOBALS['memberConnected']->image_url);
?>" width="64px"></a>
                        <ul>
                            <li class="name"><a href="#" ><?= $GLOBALS['memberConnected']->first_name . '  ' . $GLOBALS['memberConnected']->last_name; ?></a></li>
                            <a href="<?= $this->url(array('module' => 'frontend', 'controller' => 'account', 'action' => 'display'), 'default', true); ?>" class="upgrade_small"   title="Upgrade PRO"><?= $this->t('Account settings') ?></a>
                        </ul>
                    </div>
                    </p>
                    <a href="<?= $this->url(array('module' => 'frontend', 'controller' => 'point', 'action' => 'becomeverify'), 'default', true); ?>" class="sidebar_add" title="Send Message"><?= $this->t('Devenir membre verifié') ?></a> 
                    <br/>
                    <a href="<?= $this->url(array('module' => 'frontend', 'controller' => 'profile', 'action' => 'becomepremium'), 'default', true); ?>" class="sidebar_add" title="Send Message"><?= $this->t('devenir membre premium') ?></a>
                    <nav style="margin-top: 8px; background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; margin-bottom: 1em !important; overflow: hidden; padding: 0.5em 0.5em 0 !important;">
                        <ul>
                            <li class="inbox">
                                <a href="<?= $this->url(array('module' => 'frontend', 'controller' => 'contact', 'action' => 'listmycontact'), 'default', true); ?>"><?= $this->t('Mes contacts') . "(110)" ?></a>
                            </li>
                            <li class="inbox">
                                <a href="#" title="Connections"><?= $this->t('Mes visiteurs') . "(22)" ?></a>
                            </li>
                            <li class="inbox">
                                <a href="#" title="Connections"><?= $this->t('Mes points') . "(12)" ?></a>
                            </li>
                            <li class="inbox">
                                <a href="#" title="Connections"><?= $this->t('Mes affaires') . "(6)" ?></a>
                            </li>
                            <li class="inbox">
                                <a href="<?= $this->url(array('module' => 'frontend', 'controller' => 'profile', 'action' => 'addcompany'), 'default', true); ?>" class="" ><?= $this->t('My Companies') ?></a>
                            </li>
                        </ul>
                    </nav>

                    <nav style="margin-top: 8px; background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; margin-bottom: 1em !important; overflow: hidden; padding: 0.5em 0.5em 0 !important;">
                        <ul>
                            <li class="inbox">
                                <h2><?= $this->t('Mes messages') ?></h2>

                            </li>
                        </ul>
                    </nav>
                    <nav style="margin-top: 8px; background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; margin-bottom: 1em !important; overflow: hidden; padding: 0.5em 0.5em 0 !important;">
                        <ul>
                            <li class="inbox">
                                <h2><?= $this->t('Dernier inscrits') ?></h2>
                                <ul>
                                    <?php
                                    foreach ($GLOBALS['lastContactInscribed'] as $lastMember):
                                    $member = new Member();
                                    $member = $member->getMember($lastMember->member_id);
                                    ?>
                                    <div class="avatar">
                                        <a href="#" ><img alt="Default_thumb"  src="<?=
                                    $this->baseUrl() . '/images/Profil/' . $this->escape($member->image_url);
                                    ?>" height="30px"></a>
                                        <font color=blue><?= $member->first_name . '  ' . $member->last_name; ?></font>
                                        <img  src="/images/button.png" alt="Default_thumb" style="height: 30px;width: 30px; float: right">

                                    </div>


                                    <?php endforeach; ?>
                                </ul>
                                <a href="<?= $this->url(array('module' => 'frontend', 'controller' => 'profile', 'action' => 'displaysuggestmember'), 'default', true); ?>"><?= $this->t('Voir toute la liste') ?></a>


                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
