<script>
    
    /**
     * Add a comment to Wall post
     */
    function  sendMsgForSponsor(firstname,lastname,email){
         
        $.ajax({
                  
            type: "POST",                                                                                  
            url: "<?php echo $this->url(array('module' => 'frontend', 'controller' => 'point', 'action' => 'sendmsgsponsor'), 'default', true); ?>",
            async: false,
            cache: false,
            timeout: 30000,
            data: "firstname="+firstname+"&lastname="+lastname+"&email="+email,
     
            success: function(resp){
                if(resp){
                    $('#result_parain').html(resp);                    
                }
            },
            error: function(resp){
                alert('une erreur s\'est produite');
            }
        });
    }
    
    /**
     * Page loaded
     */     
    $(document).ready(function() {                          
        catchEventsLayout();
    });
       
    /**
     * de
     */
    
</script>
<aside id="rail" role="complementary">
    <div class="widget profile_completion" style="background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; padding:1.5em;">
        <div class="progress_bar">
            <?php
            $value = $GLOBALS['instanceMembre']->calculateProfileCompletion(App_Utilities::getIdMember());
            ?>
            <p>                
                <b>Profile completion</b>
            </p>
            <div class="progress" style="width:<?= $value . '%' ?>">
                <?= $value; ?>%
            </div>
        </div>
    </div>
    <div class="widget importing" style="background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; padding:1em;">
        <h5><?= $this->t('les personnes consulte profil') ?></h5>
        <br>
        <ul>
            <?php
            for ($i = 1; $i < 6; $i++):
                $member = new Member();
                $member = $member->getMember($GLOBALS['SuggestMember'][$i]['item_id']);
                ?>
                <div class="avatar">
                    <a href="#" ><img alt="Default_thumb"  src="<?=
            $this->baseUrl() . '/images/Profil/' . $this->escape($member->image_url);
                ?>" height="30px"></a>
                    <font color=blue><?= $member->first_name . '  ' . $member->last_name; ?></font>
                </div>


            <?php endfor; ?>
        </ul>
    </div>

    <div class="widget importing" style="background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; padding:1.5em;">
        <h2><?= $this->t('Inviter un contact') ?></h2>
        <?php
        $p = new SponsorForm();
        echo $p;
        ?>
        <h3>
            <div id="result_parain" >

            </div>
        </h3>
    </div>

    <div class="input_set" style="background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; padding:1.5em;">
        <div class="widget">
            <h2><?= $this->t('Publicite') ?></h2>
            <a href="#" ><img alt="Default_thumb"  src="<?=
        $this->baseUrl() . '/images/publicite/pub1.jpg';
        ?>" height="250px"></a>
            <!--
            <p class="center">
                <a class="green_button" href="#" title="">
                    button
                </a>
            </p>
            -->
        </div>
    </div>    

</aside>