<script>
    
    /**
     * Add a comment to Wall post
     */
    function  sendMsgForSponsor(firstname,lastname,email){
         
        $.ajax({
                  
            type: "POST",                                                                                  
            url: "<?php echo $this->url(array('module' => 'frontend', 'controller' => 'point', 'action' => 'sendmsgsponsor'), 'default', true); ?>",
            async: false,
            cache: false,
            timeout: 30000,
            data: "firstname="+firstname+"&lastname="+lastname+"&email="+email,
     
            success: function(resp){
                if(resp){
                    $('#result_parain').html(resp);                    
                }
            },
            error: function(resp){
                alert('une erreur s\'est produite');
            }
        });
    }
    /**
     * Add a comment to Wall post
     */
     //    function  searchcontact(word,status){
//         
//        $.ajax({
//                  
//            type: "POST",                                                                                  
//            url: "<?php echo $this->url(array('module' => 'frontend', 'controller' => 'contact', 'action' => 'listmycontact'), 'default', true); ?>",
//            async: false,
//            cache: false,
//            timeout: 30000,
//            data: "filter="+word,
//     
//            success: function(resp){
//                if(resp){
//                    $('#abcd').html(resp);                    
//                }
//            },
//            error: function(resp){
//                alert('une erreur s\'est produite');
//            }
//        });
//    }     
    /**
     * Page loaded
     */     
    $(document).ready(function() {                          
        catchEventsLayout();
    });
       
    /**
     * de
     */
    
</script>
<aside id="rail" role="complementary">
    <div class="widget profile_completion" style="background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; padding:1.5em;">
        <div class="progress_bar">
            <?php
            $member = new Member();
            $value = $member->calculateProfileCompletion(App_Utilities::getIdMember());
            ?>
            <p>                
                <b>Profile completion</b>
            </p>
            <div class="progress" style="width:<?= $value . '%' ?>">
                <?= $value; ?>%
            </div>
        </div>
    </div>
    <nav style="margin-top: 8px; background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; margin-bottom: 1em !important; overflow: hidden; padding: 0.5em 0.5em 0 !important;">
        <ul>
            <li class="inbox">
                <h2><?= $this->t('Recherche') ?></h2>

                <?php
                $p = new SearchForm();
                echo $p;
                ?>

            </li>
        </ul>
    </nav>
    <nav style="margin-top: 8px; background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; margin-bottom: 1em !important; overflow: hidden; padding: 0.5em 0.5em 0 !important;">
        <ul>
            <li class="inbox">
                <a href="#"><?= $this->t('Les connaissez-vous ?') ?></a>
                <ul>
                    <?php
                    for ($i = 1; $i < 6; $i++):
                        $member = new Member();
                        $member = $member->getMember($GLOBALS['SuggestMember'][$i]['item_id']);
                        ?>
                        <div class="avatar">
                            <a href="#" ><img alt="Default_thumb"  src="<?=
                    $this->baseUrl() . '/images/Profil/' . $this->escape($member->image_url);
                        ?>" height="30px"></a>
                            <font color=blue><?= $member->first_name . '  ' . $member->last_name; ?></font>
                            <img  src="/images/button.png" alt="Default_thumb" style="height: 30px;width: 30px; float: right">

                        </div>


                    <?php endfor; ?>
                </ul>
                <a href="<?= $this->url(array('module' => 'frontend', 'controller' => 'profile', 'action' => 'displaysuggestmember'), 'default', true); ?>"><?= $this->t('Voir toute la liste') ?></a>
            </li>
        </ul>
    </nav>
    <div class="widget importing" style="background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; padding:1.5em;">
        <h2><?= $this->t('Inviter un contact') ?></h2>
        <?php
        $p = new SponsorForm();
        echo $p;
        ?>
        <h3>
            <div id="result_parain" >

            </div>
        </h3>
    </div>

</aside>