<?php
/**
 * Manages the permissions for the given group
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_groups
 * @copyright company
 */

$config = array();
$config['pageTitle'] = sprintf('Edit Flippers for "%s" group',$this->item['name']);

echo $this->partial(
    'partials/default-add-edit.phtml',
    array(
        'form' => $this->form,
        'config' => $config
    )
);