<?php
/**
 * Displays the 404 - Page not found error
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_error
 * @copyright company
 */
?>

<div id="errorpage" class="clearfix">
    <h1>Page not found</h1>
    <p>
        The URL you requested was not found.
    </p>
    <p><a href="javascript:history.back();">← Go back</a></p>
</div>
<script type="text/javascript" charset="utf-8">
    // Random 404 lolcats
    $(document).ready(function(){
        var imgTotal=7;
        var randomNumber = Math.round(Math.random()*(imgTotal-1))+1;
        var imgPath=('/images/error-404-0'+randomNumber+'.gif');
        var img = $("<img>").attr({
            'src': '<?php echo $this->baseUrl();?>/images/error-404-0' + randomNumber + '.gif',
            'class': 'error404',
            'alt': 'Error 404',
            });
        $('div#errorpage').prepend(img);
    });
</script>