<?php
/**
 * Displays the forbidden error
 *
 * @category frontend
 * @package frontend_views
 * @subpackage frontend_views_error
 * @copyright company
 */
?>
<div style="padding:5px; border: 2px solid red" class="box box-100"><!-- box full-width --> 
    <div class="boxin"> 
        <div id="errorpage" class="clearfix">
            <h1>You do not have access to this functionality</h1>
            <p>
                We invite you to <a style="display:inline;" class="alt" href="#">subscribe</a> to an offer and be premium member                         
                <a class="alt" href="javascript:history.back();">← Go back</a>
            </p>
        </div>
    </div> 
</div>