
<p style="margin:0; padding:0;"><font face="Arial, Helvetica, sans-serif" color="#1a5e96" 
                                      style="font-size:18px; font-weight:bold;">
    Bienvenue <?= $this->firstname ?>,</font></p>


<p style="text-align:justify; font-size:13px; line-height:17px; color:#555; 
   margin:0 0 12px; padding:0;"><font face="Arial, Helvetica, sans-serif">
    Nous vous souhaitons la bienvenue et sommes ravis que vous nous ayez rejoint.</p>

<br /><br /><b>Votre compte est actuellement en attente de validation, pour valider votre inscription, 
    merci de cliquer sur ce <a href="<?= $this->lien ?>">  lien </a>.</b>


