Nous vous souhaitons la bienvenue et sommes ravis que vous nous ayez rejoint.<br />


Pour vous connectez sur  <a href="http://www.entrepreneur.ma/"><font color="#1a5e96">www.entrepreneur.ma
    <sup>&reg;</sup></font></a> 

<br/>
<font color="#1a5e96">Utilisateur :</font>
<font color="#555555"><?= $this->emailClient ?></font>
<br/>
<font color="#1a5e96">Mot de passe :</font>                   
<font color="#555555"><?= $this->password ?></font>


