<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Entrepreneur.fr, mail générique</title>
</head>

<body bgcolor="#ffffff" style="font-family:Arial, Helvetica, sans-serif; margin:0; padding:0 0 30px;">

<style type="text/css" media="screen">

body { 
	font-family:Arial, Helvetica, sans-serif;
	background-color:#ffffff;
	margin:0;
	padding:0 0 30px;
	line-height:25px;
}
a { border: none; text-decoration:none; }
img { border: none; text-decoration:none; }
a img { border: none; }
table { border-collapse:collapse; }
table td { padding:0; }

/* REP SKIN : http://www.entrepreneur.fr/skins/entrepreneur/mail/ */

</style>

<table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif; border-collapse:collapse;">
	<tr><td align="center" valign="top">

		<table width="100%" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
			<tr><td align="center" valign="middle" style="padding:3px 0 0; font-size:11px; color:#999999;">
				<i>Pensez à ajouter <a href="#" style="text-decoration:none; color:#999;"><font color="#999999">info@entrepreneur.fr</font></a> à vos contacts</i>.</font> 
			</td></tr>
		</table>
	
		<table width="590" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
			<tr>
				
				<!-- Main column -->
				<td align="left" valign="top" bgcolor="#ffffff">
				
					<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
						<tr><td align="left" valign="top">
							<a href="http://www.entrepreneur.fr/" style="text-decoration:none;"><img border="0" src="<?= $this->site; ?>/styles/mails/logo_mail.gif" alt="" /></a>
						</td>
						<td align="right" valign="top">
							<a href="http://www.entrepreneur.fr/" style="text-decoration:none;"><img border="0" src="<?= $this->site; ?>/styles/mails/img_header-baseline.gif" alt="" /></a>
						</td></tr>
					</table>
					
					<!-- HEADER end -->
				
					<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
						<tr><td align="center" valign="top">
							<img border="0" style="display:block;" src="<?= $this->site; ?>/styles/mails/img_center-top.gif" alt="" />
						</td></tr>
					</table>
					
					<!-- CENTERTOP end -->
				
					<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
						<tr>
							<td align="center" valign="top">
								
								<!-- Tableau conteneur -->	
								<table bgcolor="#ffffff" width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
									<tr>
									
									<!-- Shadow left -->
									<td align="right" valign="top" width="15"><img border="0" style="display:block;" src="<?= $this->site; ?>/styles/mails/img_shadowglobal-left.jpg" alt="" /></td>
									
									<td align="center" valign="top">
									
				<!-- GLOBAL MAIL END -->
									
				<!-- CONTENU MAIL -->
									
									<!-- Tableau contenant -->
									<table bgcolor="#ffffff" width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
										<tr><td align="center" valign="top" bgcolor="#dddddd">
																	
										<table width="100%" bgcolor="#16619e" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
											<tr>
												<td align="left" valign="top">
													<!-- Attention, si titre trop long, commenter ce table et metter le titre en dessous -->
													<p style="margin:0 10px 3px; padding:0; text-align:center;"><font face="Arial, Helvetica, sans-serif" color="#ffffff" style="font-size:20px; text-transform:uppercase;"><?= $this->sujetMail; ?></font></p>
												</td>
											</tr>
										</table>

										<!-- Tableau contenant 2 -->
										<table bgcolor="#ffffff" width="558" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
											<tr><td align="left" valign="top">
																	
												<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
													<tr>
														<td align="left" valign="top" style="padding:20px;">
															<p style="margin:0; padding:0;"><font face="Arial, Helvetica, sans-serif" color="#3994b5" style="font-size:20px;"><?= $this->h1Mail; ?></font></p>
														</td>
													</tr>
													<tr>
														<td align="left" valign="top" style="padding:0 20px 20px;">
