</td>
													</tr>
												</table>
												
												<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
													<tr>
														<td align="center" valign="middle">
															<img border="0" style="display:block;" src="<?= $this->site; ?>/styles/mails/img_center-shadow-separ.gif" alt="" />
														</td>
													</tr>
												</table>
									
				<!-- CONTENU END -->
									
				<!-- FOOTER -->
												
												<!-- Footer -->
												<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
													<tr>
														<td align="center" valign="middle">
															<img border="0" style="display:block;" src="<?= $this->site; ?>/styles/mails/img_footer-top.gif" alt="" />
														</td>
													</tr>
												</table>	
												<table width="100%" bgcolor="#fcfcfc" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
													<tr>
														<td align="left" valign="middle" style="padding:10px;">
															<font face="Tahoma, Geneva, sans-serif" style="font-size:15px;" color="#777777">
																A très bientôt, <br />
																L'équipe Entrepreneur.fr<sup>&reg;</sup>
															</font>
														</td>
                                                        <td align="right" valign="middle" style="padding:10px;">
															<a href="http://www.entrepreneur.fr/">
																<img src="<?= $this->site; ?>/styles/mails/bgd_logoImgFooter.gif" alt="" />
															</a>
                                                        </td>
													</tr>
												</table>	
				
											</td></tr>
										</table><!-- Tableau contenant 2 end -->
				
										</td></tr>
									</table><!-- Tableau contenant end -->
									
									<!-- Shadow right -->
									<td align="left" valign="top" width="15"><img border="0" style="display:block;" src="<?= $this->site; ?>/styles/mails/img_shadowglobal-right.jpg" alt="" /></td>
									
									</td></tr>
								</table><!-- Tableau conteneur end -->

								<table width="100%" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
									<tr><td align="center" valign="top"><img border="0" style="display:block;" src="<?= $this->site; ?>/styles/mails/img_footer.gif" alt="" /></td></tr>
									<tr><td align="center" valign="top" style="padding:10px 0;">
										<font face="Arial, Helvetica, sans-serif" color="#777777" style="font-size:11px;">
											<a href="http://www.entrepreneur.fr/"><font color="#1a5e96">Entrepreneur.fr<sup>&reg;</sup></font></a> - <?= date('Y'); ?> - Tous droits réservés.
										</font>
									</td></tr>
								</table>
									
							</td>
						</tr>
					</table>
					
					<!-- CENTER end -->

				</td>
				<!-- Main column end -->

			</tr>
		</table>
	
	</td></tr>
</table>

</body>

</html>
