<script type="text/javascript">
    $(document).ready(function(){
     
        $('.category').click(function(){
            var category=  $(this).attr("id");
            $.ajax({
               url : '<?php echo $this->url(array('controller' => 'business', 'action' => 'findskills'), 'default', true); ?>',
               data :'category='+category,
                type : 'POST',
                success : function(responseText){
                    $('#skills').html(responseText);
                }
            });
        })
        $('.checkbox').live("click", function(){
            var skills=  $(this).attr("id");
            if($(this).is(":checked")) {
                $.ajax({
                    url : '<?php echo $this->url(array('controller' => 'business', 'action' => 'putskills'), 'default', true); ?>',
                    data :'skills='+skills,
                    type : 'POST',
                    success : function(responseText){
                        $('#skillsselected').append(responseText);
                    }
                });
            } else {
                
            }

        
        });
          
    });

</script>
<div id="sidebar">
    <div class="sidebar_user">
        <div class="fields">
            <div class="input_set">
                <center><div class="input_set">
                        <p>
                        <div id="self_card">
                            </p><br/>
                            <nav style="margin-top: 8px; background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; margin-bottom: 1em !important; overflow: hidden; padding: 0.5em 0.5em 0 !important;">
                                <ul>
                                    <li class="inbox">
                                        <div id="list-body">
                                            <table class="sample">
                                                <thead><tr><th><u>Choisissez une category</u></th></tr></thead>
                                                <tbody >
                                                    <?php foreach ($this->categoryProject as $row): ?>
                                                        <tr><td><a href='#' class="category" id="<?= $row->category_id; ?>"><?= $row->category_description; ?></a></td></tr>
                                                    <?php endforeach; ?>
                                                </tbody>
                                            </table>
                                            <br/>                 
                                            <div><?php //$this->paginationControl($this->projects, $scrollingStyle = null, 'paginators/ajax.phtml', array('jsFunctionName' => 'getList'));    ?></div>
                                        </div>
                                    </li>
                                </ul>
                            </nav></div></div></center></div></div></div></div><br/><br/><br/>
<table class="sample" style="clear: right">
    <thead><tr><th><u>Choisissez les competences</u></th></tr></thead>
<tbody id="skills">

</tbody>
</table><br/><br/>
<table class="sample" style="clear: right">
    <thead><tr><th><u> competences selectionné</u></th></tr></thead>
<tbody id="skillsselected">

</tbody>
</table>