<div id="sidebar">
    <div class="sidebar_user">
        <div class="fields">
            <div class="input_set">
                <center><div class="input_set">
                        <p>
                        <div id="self_card">
                            </p><br/>
                            <nav style="margin-top: 8px; background: none repeat scroll 0 0 #EFEFEF; border-radius: 0.5em 0.5em 0.5em 0.5em; margin-bottom: 1em !important; overflow: hidden; padding: 0.5em 0.5em 0 !important;">
                                <ul>
                                    <li class="inbox">
                                 
                                    <div id="list-body">
                               <table class="sample">
    <thead><tr><th><u>Choisissez une category</u></th></tr></thead>
    <tbody>
        
</tbody>
</table>
                                   
                                        <div><?php //$this->paginationControl($this->projects, $scrollingStyle = null, 'paginators/ajax.phtml', array('jsFunctionName' => 'getList')); ?></div>
                                    </div>
                                    </li>
                                </ul>
                            </nav></div></div></center></div></div></div></div>