<?php
/**
 * Delete a privilege
 *
 * @category backoffice
 * @package backoffice_views
 * @subpackage backoffice_views_privileges
 * @copyright company
 */

$config = array();
$config['pageTitle'] = 'Delete privilege';
$config['areYouSureMessage'] = 'Are you sure you want to delete the privilege?';

// column names & indexes
$config['columnNames'] = array(
    'Name',
    'Flag',
    'Description',
);
$config['columnIndexes'] = array(
    'name',
    'flagName',
    'description'
);

echo $this->partial(
    'partials/default-delete.phtml',
    array(
        'form' => $this->form,
        'config' => $config,
        'item' => $this->item
    )
);