<div class="data-table">
    <table cellspacing="0" cellpadding="0"> 
        <thead>
            <tr> 
                <th scope="col" class="first"><span>ID</span></th>
                <th scope="col"><span>Talent</span></th>
                <th scope="col"><span>Roles</span></th>
                <th scope="col"><span>Membership</span></th>
                <th scope="col" class="last"><span>Action</span></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">325</th>
                <td><a href="#">Billy Crystal</a></td>
                <td>Contorsionist</td>
                <td>Premium</td>
                <td>
                    <ul class="actions">
                        <li><a href="#" class="edit">Edit</a></li>
                        <li><a href="#" class="delete">Delete</a></li>
                    </ul>
                </td>
            </tr>
            <tr>
                <th scope="row">325</th>
                <td><a href="#">Billy Crystal</a></td>
                <td>Contorsionist</td>
                <td>Premium</td>
                <td>
                    <ul class="actions">
                        <li><a href="#" class="edit">Edit</a></li>
                        <li><a href="#" class="delete">Delete</a></li>
                    </ul>
                </td>
            </tr>
            <tr>
                <th scope="row">325</th>
                <td><a href="#">Billy Crystal</a></td>
                <td>Contorsionist</td>
                <td>Premium</td>
                <td>
                    <ul class="actions">
                        <li><a href="#" class="edit">Edit</a></li>
                        <li><a href="#" class="delete">Delete</a></li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<ul class="grid clearfix">
    <li class="item">
        <a class="thumb" href="#"><img src="tmp/user-01.png" alt=""></a>
        <div class="data">
            <h4><a href="#">Billy Crystal</a> <span class="id">#325</span></h4>
            <p class="roles">
                Contorsionist, Singer
            </p>
            <p class="membership">
                Premium Member
            </p>
        </div>
        <ul class="actions">
            <li><a href="#" class="edit">Edit</a></li>
            <li><a href="#" class="delete">Delete</a></li>
        </ul>
    </li>
    <li class="item">
        <a class="thumb" href="#"><img src="tmp/user-01.png" alt=""></a>
        <div class="data">
            <h4><a href="#">Billy Crystal</a> <span class="id">#325</span></h4>
            <p class="roles">
                Contorsionist, Singer
            </p>
            <p class="membership">
                Premium Member
            </p>
        </div>
        <ul class="actions">
            <li><a href="#" class="edit">Edit</a></li>
            <li><a href="#" class="delete">Delete</a></li>
        </ul>
    </li>
    <li class="item last">
        <a class="thumb" href="#"><img src="tmp/user-01.png" alt=""></a>
        <div class="data">
            <h4><a href="#">Billy Crystal</a> <span class="id">#325</span></h4>
            <p class="roles">
                Contorsionist, Singer
            </p>
            <p class="membership">
                Premium Member
            </p>
        </div>
        <ul class="actions">
            <li><a href="#" class="edit">Edit</a></li>
            <li><a href="#" class="delete">Delete</a></li>
        </ul>
    </li>
    <li class="item">
        <a class="thumb" href="#"><img src="tmp/user-01.png" alt=""></a>
        <div class="data">
            <h4><a href="#">Billy Crystal</a> <span class="id">#325</span></h4>
            <p class="roles">
                Contorsionist, Singer
            </p>
            <p class="membership">
                Premium Member
            </p>
        </div>
        <ul class="actions">
            <li><a href="#" class="edit">Edit</a></li>
            <li><a href="#" class="delete">Delete</a></li>
        </ul>
    </li>
</ul>